import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

// Components
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

import NextTopLoader from "nextjs-toploader";

import favicon from '/public/images/favicon.ico'

const kanit = Kanit(
  {
    subsets: ["latin", "thai"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
  }
);

export const metadata: Metadata = {
  title: "about2day",
  description: "Generated by create next app",
  icons: [
    {
      rel: 'icon',
      url: favicon.src
    }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className} suppressHydrationWarning={true}>
        <NextTopLoader
          color="#865DFF"
          shadow="0 0 10px #865DFF,0 0 5px #865DFF"
          showSpinner={false}
        />
        <div className="bg-clr-dark text-clr-light min-h-screen">
          <Navbar />
          <main className="py-16 px-24 max-xl:px-16 max-lg:px-4">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
